### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by fperezw** [wizzard366/quiniela2018#12]
La pagina de Login no muestra errores cuando el usuario no puede ingresar. Un mensaje de "el usuario no esta activo/ password incorrecto" falta algo asi.

**Comment by ajoliva** [comment]
El API regresa mensajes de error junto al codigo HTTP, se puede hacer que despliegue ese mismo mensaje o en base al codigo de respuesta desplegar otro establecido desde el FE

**Comment by wizzard366** [comment]
Se agregó mensaje de error.
