### ISSUE TITLE
cambios en tabla prediction API

### ISSUE THREAD

**Issue by fperezw** [wizzard366/quiniela2018#8]
Antonio, Ken y yo decidimos agregar una columna más a la tabla de predicciones, se llama QualifyId y va a ser utilizada unicamente en los partidos de eliminatoria directa (a partir de la fase 2) pero obviemente tiene que estar en la tabla.

Lo que hay que actualizar es el API para que se pueda guardar este campo con el ID de el equipo que clasifica en la llave. En los partidos de grupos se se puede mandar null.

Esta columna también va a estar en la tabla de games para poder después comparar a la hora de sumar puntos

**Comment by ajoliva** [comment]
Cambios ya en master.

**Comment by fperezw** [comment]
buenisimo, cuando Taracena termine su parte y probemos, cerramos este issue

**Comment by fperezw** [comment]
Este ya quedó también, saludos
