### ISSUE TITLE
Cambio en tabla predictions front-end

### ISSUE THREAD

**Issue by fperezw** [wizzard366/quiniela2018#9]
Mario, Ken y yo decidimos agregar una columna más a la tabla de predicciones, se llama QualifyId y va a ser utilizada unicamente en los partidos de eliminatoria directa (a partir de la fase 2) pero obviamente tiene que estar en la tabla.

Lo que hay que actualizar es el front-end para que se pueda guardar este campo con el ID de el equipo que clasifica en la llave. En los partidos de grupos se se puede mandar null.

Esta columna también va a estar en la tabla de games para poder después comparar a la hora de sumar puntos

En resumen esto hay que hacer: 

- todo lo que sea la fase 1, se guarda igual y ese campo se manda como null.
- lo que sea fase 2 en adelante, solo en caso que el usuario haya ingresado un empate, un campo de ganador se muestra al usuario para resolver el empate y guardarlo en ese campo.
- En caso que el usuario ingrese un ganador, este campo tiene el mismo valor que el de winner ID

**Comment by wizzard366** [comment]
El Id no se puede mostrar en la tabla, tiene que ser el nombre del equipo, pregunta: el QualifyId tiene que ser si o si uno de los 2 el game o prediction o null?

**Comment by wizzard366** [comment]
Se agregó entradas a las tablas de predicciones y partidos, y se agregaron los campos correspondientes a agregar predicción y a actualizar predicción.
